
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(10001,  'Ranga', 'Hyderabad', CURRENT_TIMESTAMP());

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(10002,  'James', 'New York',CURRENT_TIMESTAMP());

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES(10003,  'Pieter', 'Amsterdam',CURRENT_TIMESTAMP());